// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResolveHost(arg1) {
  return window['go']['detector']['DNS']['ResolveHost'](arg1);
}
