// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreHandle() {
  return window['go']['detector']['MTR']['PreHandle']();
}

export function TryMTR(arg1) {
  return window['go']['detector']['MTR']['TryMTR'](arg1);
}
