// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function TryPing(arg1) {
  return window['go']['detector']['Ping']['TryPing'](arg1);
}
