// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {detector} from '../models';

export function TryPing(arg1:string):Promise<detector.PingResult>;
