// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreHandle():Promise<void>;

export function TryHTTPSConnection(arg1:string):Promise<void>;
