// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PreHandle() {
  return window['go']['detector']['TCPConnection']['PreHandle']();
}

export function TryHTTPSConnection(arg1) {
  return window['go']['detector']['TCPConnection']['TryHTTPSConnection'](arg1);
}
